<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>ConfirmCheck</fullName>
        <field>Confirm__c</field>
        <literalValue>1</literalValue>
        <name>要確認のチェックを付ける</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>休暇が1日以下</fullName>
        <actions>
            <name>ConfirmCheck</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>HolidayRequest__c.NumberOfHoliday__c</field>
            <operation>lessOrEqual</operation>
            <value>1</value>
        </criteriaItems>
        <criteriaItems>
            <field>HolidayRequest__c.AttentionCheck__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>休暇タイプチェック</fullName>
        <active>false</active>
        <formula>ISPICKVAL( HolidayType__c , &apos;休暇タイプの１つ&apos;)</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>休暇期間が5日を超える</fullName>
        <actions>
            <name>ConfirmCheck</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>HolidayRequest__c.NumberOfHoliday__c</field>
            <operation>greaterThan</operation>
            <value>5</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
